server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.208.16.103:3306/tutoring_database?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: tutoring
    password: wNmxf3P4r3YaAMDm
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: smtp.gmail.com
    port: 587
    username: wxinran543@gmail.com
    password: dlgyysvqolbcljep
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true


ali-oss:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  access-key-id: LTAI5tRM3FjZEZjXbNoTAUEu
  access-key-secret: 6xyVEBQPktBIYxqRE7T77rcg1zFNdW
  bucket-name: aronimage

jwt:
  secret: "YourJWTSecretKey"
  expiration: 86400000

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: tutoring-common.com.tutoring.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


knife4j:
  locale: en

google:
  clientId: "642557482063-q866pb3tlp0blvso126q2i2si40qn6oh.apps.googleusercontent.com"

